# Site Settings
title: LWT Timeline
description: Project Schedule and Review Tracking
remote_theme: just-the-docs/just-the-docs

# Since your repo is LWT_timeline.github.io, leave these as follows:
url: "https://LWT_timeline.github.io"
baseurl: ""

# Enable Mermaid
mermaid:
  version: "10"

# Set full width for the Gantt Chart
defaults:
  - scope:
      path: ""
    values:
      layout: default
      full_width: true
